name: LAPRAS Card

on:
  workflow_dispatch:
  # 週1回月曜日更新
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: 'yama-t'
          LANG: 'ja'
